### ISSUE TITLE
DefaultCommit.java:31-32: We need to split the author...

### ISSUE THREAD

**Issue by 0pdd** [llorllale/loggit-maven-plugin#28]
The puzzle `20-c33780f3` from #20 has to be resolved:

https://github.com/llorllale/gitlog-maven-plugin/blob/91eafd73bd1d3968a3c18d760d84cfa281083337/src/main/java/org/llorllale/mvn/plgn/gitlog/DefaultCommit.java#L31-L32

The puzzle was created by George Aristy on 04-Feb-18. 

Estimate: 30 minutes, role: IMP.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by llorllale** [comment]
This is not needed - won't fix
