### ISSUE TITLE
DefaultCommitTest.java:73-75: Checkstyle: enforce use of...

### ISSUE THREAD

**Issue by 0pdd** [llorllale/loggit-maven-plugin#50]
The puzzle `29-71e94be2` from #29 has to be resolved:

https://github.com/llorllale/loggit-maven-plugin/blob/bb2ac45dc2c0159fef324697fa8b76e1ee38a384/src/test/java/org/llorllale/mvn/plgn/loggit/DefaultCommitTest.java#L73-L75

The puzzle was created by George Aristy on 26-Feb-18. 

Estimate: 30 minutes, role: DEV.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by llorllale** [comment]
Dup of #34
