### ISSUE TITLE
Regex issue using <includeRegex>

### ISSUE THREAD

**Issue by Sami32** [llorllale/loggit-maven-plugin#91]
I would like filter the commits depending on their message content but my Regex string generate an error:

> [INFO] --- loggit-maven-plugin:1.0.0:changelog (Generate-ReleaseNotes) @ dms ---
> [ERROR] #fatalError(): Syntax error at char 1 in regular expression: No expression before quantifier; SystemID: file:///; Line#: 24; Column#: 15

I probably do something wrong. Here is my setting:
```
<includeRegex>(?i)^(add|fix|refactor|formatting|update|optimize|reduce|k: |synchronize|improve|enhance).*</includeRegex>
```

Any idea?
Any help will be really appreciate.

**Comment by llorllale** [comment]
@Sami32 Hi! I'm glad you're using this plugin.

I had not realized that this plugin is not supporting flags unfortunately. We're using the [`fn:matches`](https://www.w3.org/TR/xpath-functions-30/#func-matches) which is overloaded to accept flags - [these](https://www.w3.org/TR/xpath-functions-30/#flags) are the flags supported by XSLT 3.0.

I'll try to add this in by tomorrow evening - hang on!

**Comment by Sami32** [comment]
Well.. i'm trying to ;)
Thank you very much for your answer and help +1

**Comment by llorllale** [comment]
@Sami32 try version `1.0.1`.

You'll have to provide your modifiers separately in a new configuration tag `<includeRegexFlags>`. So in your case it'd look like:

```xml
<includeRegex>^(add|fix|refactor|formatting|update|optimize|reduce|k: |synchronize|improve|enhance).*</includeRegex>
<includeRegexFlags>i</includeRegexFlags>
```

**Comment by Sami32** [comment]
@llorllale It work great now :)

You was by far the most reactive and active developper that i met on such pluging kind 👍 
Thank you very much for providing us that nice piece of code 😉

**Comment by Sami32** [comment]
I should have added that you are the most documented, with sample, project.
I always found very annoying to have to look at the code to see all the options available and trying to understand them.
I know that near no one like doing documentation but it is really a breeze when you have it done IMO.
👍

**Comment by llorllale** [comment]
@Sami32 

> Perhaps you could add mvn loggit:changelog for the user wishing use it from the command line.

You mean documentation? There's this brief mention in the README:

> They are also available from the command line if you prefix them with loggit. (eg. -Dloggit.maxEntries)

Do you feel it needs to be clearer?

**Comment by Sami32** [comment]
Yes, it wasn't clear to me in the documentation, that's said i sorted it out, but if it could be avoided for the following users...
It was only my 2 cents though.
