### ISSUE TITLE
<startCommit> option

### ISSUE THREAD

**Issue by Sami32** [llorllale/loggit-maven-plugin#94]
An other suggestion will be to add <startCommit> option.
Because when you start a new project from a fork of an existing one, you generally remove all the tags and don't want all the commits from the original be added to your log, as it is not pertinent and make the process to generate the log muuuch longer.

**Comment by llorllale** [comment]
@Sami32 I just released `1.1.0-rc5`. Can you test `<startCommit>`?

**Comment by Sami32** [comment]
Done, and it work great +1
Thank you very much for that feature add that our new project need 😄
