### ISSUE TITLE
<excludeRegex> option

### ISSUE THREAD

**Issue by Sami32** [llorllale/loggit-maven-plugin#95]
~~Maybe a `deduplicate` option to avoid logging commits having the same message.~~
In case some comitters use too much the merge button, for example: "Merge branch 'master' into ..."
Or committers leaving the default Github message: "Update ..." without having been squashed before the merge.

**EDIT**:
To exclude some commits, and also because some developpers could find more easy or appropriate to define the commits exclusion than the commits inclusion Regex string.

**Comment by llorllale** [comment]
@Sami32 if we find duplicates, which one should we keep?

**Comment by Sami32** [comment]
Probably the last one, as i suspect these novice commit to be done from Github/Gitlab web interface.

Having 5 "Merge branch 'master' into ..." ugly commits in a PR shouldn't have any mean to be in a changelog and i don't think that have many "Update myfile.java" many time should either.
That said it was just an idea.

**Comment by llorllale** [comment]
@Sami32 if we don't want certain commits to appear, maybe we can introduce `<excludeRegex>`.

**Comment by Sami32** [comment]
Yes, your offer seem even better as it will have a more flexible use case.

**Comment by llorllale** [comment]
@Sami32 can you change the title and description to request this new `<excludeRegex>`? Thanks

**Comment by Sami32** [comment]
Done.

**Comment by Sami32** [comment]
Worked fine thank you 👍
